### ISSUE TITLE
强制微信扫码登录

### ISSUE THREAD

**Issue by Change72** [harryhare/1point3acres#14]
近期几个号遇到了“为了账户安全，请微信登录”的情况，并且在浏览器扫码登录后，一旦退出，还要微信登录。这种情况下，能否增加模拟浏览器扫码-> 记录cookies，来避过呢

**Comment by Change72** [comment]
![image](https://user-images.githubusercontent.com/29840570/132996811-a5eab0b8-f708-45ff-a9f5-a5e77bbccf64.png)

使用cookie也有问题，如果在另一台机器或者浏览器登录的话，保存的cookie会不会失效呢。。。即单点登录

**Comment by harryhare** [comment]
记录cookie 应该也是可以的，我记得之前cookie 是相互不影响的，也就是另外一个浏览器登录后，当前的cookie 并不会失效

**Comment by harryhare** [comment]
代码加上了

**Comment by Change72** [comment]
为大佬点赞！我自己用Selenium也行得通~
