### ISSUE TITLE
问题没收录 question not found

### ISSUE THREAD

**Issue by Lurkrazy** [harryhare/1point3acres#17]
do daily question...
get question...
form hash: 10bb9afa
question: 下面哪些言论，在一亩三分地里算违规？
answers: {'2': 'A国的同事都如何如何', '3': '某地区的同学都如何如何', '4': '这些以偏概全的说法都不推荐', '1': '"女生都xyz”， “男生都xyz”'}
question not found

**Comment by harryhare** [comment]
已更新，感谢
