### ISSUE TITLE
部分账号被封，出现503错误

### ISSUE THREAD

**Issue by Change72** [harryhare/1point3acres#18]
do daily checkin...
get checkin info error: status code is 503

并且今天凌晨突然封了几个号，直接【禁止访问】用户组。之前还会有个账号异常的中间阶段

**Comment by Change72** [comment]
现在情况是

**Comment by Change72** [comment]
线上服务器linux和windows都不行，阿里云和aws服务器都不行
本地是win，但莫名其妙被系统封了好多个，只不过剩下的还能继续签

**Comment by Change72** [comment]
线上服务器linux和windows都不行，境内阿里云和境外aws服务器都不行
本地是win，但莫名其妙被系统封了好多个，只不过剩下的还能继续签

**Comment by Change72** [comment]
https://www.1point3acres.com/bbs/?__cf_chl_jschl_tk__=pmd_UDsUrhYS6avG0ME7QDMWvg_hCkiOCFNhWXy3xoD1ko0-1635923152-0-gqNtZGzNAlCjcnBszQpR

现在的打开主页会自动带上额外的参数，不知道是不是这个原因，win的服务器通过浏览器能打开，但命令行签到不行

**Comment by harryhare** [comment]
> 现在情况是 线上服务器的号，全部503。已经换了好几个服务器ip了，还是503 本地的号，被封了好几个，就是毫无征兆，也没有多地登录的号，凌晨突然被封了好几个 但是本地剩余的号，还是可以继续签到

503 的话应该是被cloudflare的五秒盾挡住了。cloudflare 的五秒盾应该会特意关照云服务器的ip，所以服务器ip更容易被封

**Comment by harryhare** [comment]
> do daily checkin... get checkin info error: status code is 503
> 
> 并且今天凌晨突然封了几个号，直接【禁止访问】用户组。之前还会有个账号异常的中间阶段

一亩三分地的bug 也有可能导致被封号。封号就给他们开个ticket，不要跟他们说脚本，只跟他们说是登录有问题，上次有个号就这样要回来了

**Comment by harryhare** [comment]
> https://www.1point3acres.com/bbs/?__cf_chl_jschl_tk__=pmd_UDsUrhYS6avG0ME7QDMWvg_hCkiOCFNhWXy3xoD1ko0-1635923152-0-gqNtZGzNAlCjcnBszQpR
> 
> 现在的打开主页会自动带上额外的参数，不知道是不是这个原因，win的服务器通过浏览器能打开，但命令行签到不行

嗯嗯，这个参数就是 cf 的五秒盾加的，以前试过很多办法都没法解掉这个东西。一般解这个是用Selenium，但是我没有跑通，我用 selenium 也还是卡在 cloudflare 的加载页面。

**Comment by Change72** [comment]
> > https://www.1point3acres.com/bbs/?__cf_chl_jschl_tk__=pmd_UDsUrhYS6avG0ME7QDMWvg_hCkiOCFNhWXy3xoD1ko0-1635923152-0-gqNtZGzNAlCjcnBszQpR
> > 现在的打开主页会自动带上额外的参数，不知道是不是这个原因，win的服务器通过浏览器能打开，但命令行签到不行
> 
> 嗯嗯，这个参数就是 cf 的五秒盾加的，以前试过很多办法都没法解掉这个东西。一般解这个是用Selenium，但是我没有跑通，我用 selenium 也还是卡在 cloudflare 的加载页面。

这个我有点经验，在我的尝试中 selenium + chrome + --user-data-dir，可以过cloudflare。但是--user-data-dir只有主账户一个用户，其他情况都跑不通了。也就是说目前我用selenium的进展是只能单用户。

比如 chrome 创个profile 或者是在启动前注入cookie我都试过，都过不去cloudflare。。就比较难搞

**Comment by Change72** [comment]
> > do daily checkin... get checkin info error: status code is 503
> > 并且今天凌晨突然封了几个号，直接【禁止访问】用户组。之前还会有个账号异常的中间阶段
> 
> 一亩三分地的bug 也有可能导致被封号。封号就给他们开个ticket，不要跟他们说脚本，只跟他们说是登录有问题，上次有个号就这样要回来了

提工单试试运气吧。。。我认识的一个老哥，半年前提的工单到现在都没解封。。。
