### ISSUE TITLE
用cookie登陆，提示错误

### ISSUE THREAD

**Issue by lu9999** [harryhare/1point3acres#26]
do daily checkin...
sec hash not found 未知错误，查看tmp.html，了解详情
check in 未知错误，查看tmp.html，了解详情
do daily question...
get question...
Traceback (most recent call last):
  File "service.py", line 153, in <module>
    main()
  File "service.py", line 139, in main
    do_all_cookie(solver, user["cookie"])
  File "service.py", line 112, in do_all_cookie
    daily_question(solver)
  File "service.py", line 99, in daily_question
    answer, form_hash, sec_hash, = get_daily_task_answer()
  File "/volume1/homes/Luyao/src/1point3acres/src/raw_requests.py", line 342, in get_daily_task_answer
    form_hash_node = nodes[1].cssselect('form input[name="formhash"]')[0]
IndexError: list index out of range

tmp.html也只是正常的签到页面，没有error

**Comment by harryhare** [comment]
看上似乎去是网页改版导致的。每个出错的 tmp.html 都发一下吧？

**Comment by harryhare** [comment]
我刚试了一下我的账号依然正常。。。没法复现太坑了。。。

**Comment by lu9999** [comment]
[tmp.html.zip](https://github.com/harryhare/1point3acres/files/8192036/tmp.html.zip)

**Comment by harryhare** [comment]
中间的报错信息乱码了。。
![微信图片_20220308223148](https://user-images.githubusercontent.com/3347974/157258652-6e4010d9-49cd-49ab-a1db-eadb8abb34fe.png)

**Comment by lu9999** [comment]
> 似乎是说什么错误，我改了一下写tmp.html的方式，拉下代码再试下？

拉了，新的tmp.html 显示 如想继续签到，请使用一亩三分地手机APP登录，登录后可在手机或网页端签到。
更录完后一切正常了，谢谢
