### ISSUE TITLE
手动起了workflow后一直是queued状态

### ISSUE THREAD

**Issue by Allennn-An** [harryhare/1point3acres#3]
手动起了workflow后一直是queued状态，一个小时都没变化这是什么bug吗

**Comment by harryhare** [comment]
github action 故障了，官方还在维护中，https://www.githubstatus.com/

**Comment by harryhare** [comment]
我看到最近的一次schedule 已经正常执行，我把issue关了吧

**Comment by Allennn-An** [comment]
刚刚论坛看了下，我这边每日答题似乎没完成，显示答题中，是因为题库里没有这个题吗

**Comment by harryhare** [comment]
看了下题库里面有，日志比较奇怪，直接停了啥都没输出。似乎是解析出的答案多了前后两个空格。我改下。

**Comment by harryhare** [comment]
你拉下代码再试试？
