### ISSUE TITLE
新问题

### ISSUE THREAD

**Issue by Lurkrazy** [harryhare/1point3acres#31]
do daily question...
get question...
form hash: 490d6eaa
question: 遇到特别奇葩的帖子，以下哪些做法是错误的？
answers: {'2': '举报回帖为“引战钓鱼”', '1': '回帖：肯定是气氛组在冲业绩', '4': '世界很大，不自以为是，之前没见过的事情，也有可能是真的呢！', '3': '世界很大，别做井底之蛙。看不管的关掉即可。'}
question not found

**Comment by Lurkrazy** [comment]
答案是：回帖：肯定是气氛组在冲业绩

**Comment by harryhare** [comment]
加上了，感谢。
