### ISSUE TITLE
formhash not found 未知错误

### ISSUE THREAD

**Issue by wangmou20** [harryhare/1point3acres#42]
do daily checkin...之后报错

> formhash not found 未知错误，查看tmp.html，了解详情
![image](https://user-images.githubusercontent.com/17882535/197305012-ab64eca5-1341-4868-9aec-2ca2ea647a14.png)

有人知道怎么回事吗？手机试过能正常登录签到和答题

**Comment by bipindr123** [comment]
@harryhare same error, is this the tag its looking for <input type="hidden" name="formhash" value="1da3535f">

**Comment by harryhare** [comment]
这个逻辑已经改变了
