### ISSUE TITLE
github actions

### ISSUE THREAD

**Issue by pjpjq** [harryhare/1point3acres#43]
可以做成github actions吗？类似https://github.com/xiaoxiunique/schedule-bilibili

**Comment by harryhare** [comment]
两年前最开始搞得时候就是github action。但是由于 一亩三分地更新后启用了cloudflare的5秒盾，github  ci 机器的 IP 会被 拦截，所以 github action 失效。同时， github action 签到用违反了 github 的用户协议，也不太好。。。
