### ISSUE TITLE
请问为什么有时候会失败呢

### ISSUE THREAD

**Issue by continuousRiven** [harryhare/1point3acres#6]

**Comment by harryhare** [comment]
官方把接口改了。。。我看下能不能修

**Comment by harryhare** [comment]
代码改好了，本地可以跑。但是github action 还是503，估计 azure 的机器 ip 被封了，等等吧，如果晚些还不能好，就只能换其他CI了

**Comment by harryhare** [comment]
试了下代码没改之前本地也是可以跑通的，这说明 官方应该是直接疯掉了 github action 的机器的 IP。。。大概率不会好了。 还是换到其他CI，或者用本地 cron job

**Comment by harryhare** [comment]
网友Billy Zhang 把 环境改了一下勉强能用了。可以拉下最新代码重试了

**Comment by harryhare** [comment]
又看了下，好像只有我自己的和他的账号能跑通。。。好奇怪

**Comment by harryhare** [comment]
啊，终于知道问题了，cloudfare的5秒盾

**Comment by shikouchen** [comment]
在aws lambda可以跑吗

**Comment by harryhare** [comment]
> 在aws lambda可以跑吗

我的 aws lambda的几个月前就被503了

**Comment by harryhare** [comment]
目前的解决方案有一定概率能跑成功，不稳定

**Comment by tonyxiahua** [comment]
本地跑是什么意思呀……

**Comment by harryhare** [comment]
> 本地跑是什么意思呀……

如果你电脑的操作系统是 Linux 的话，加个定时任务（cron job），程序就会在你设定的时间自动跑了，当然前提是电脑开机。

或者 XX云 的 Linux 虚拟服务器也可以，但是要先测试下IP 是否倍 cloudflare 拉黑。
