### ISSUE TITLE
Looks like there are many new questions

### ISSUE THREAD

**Issue by dancju** [harryhare/1point3acres#8]
Perhaps we can make it interactive here, so that users can choose an answer in the console.

```
question: 为什么有时候一亩三分地的数据跟我感觉的平均情况相差很大？
answers: {'4': '这些都包括', '2': '越极端的数据越引人注意', '3': '发帖人自我选择来分享自己的数据，并没有自称自己代表了“平均”', '1': '越极端的数据越容易被公布'}
question not found
```

**Comment by harryhare** [comment]
其实我更倾向于做成后台自动执行的模式。再等等哈，感觉再过一周题目应该能差不多能收集齐。

**Comment by harryhare** [comment]
我一会把这道题加上

**Comment by nerddan** [comment]
> 其实我更倾向于做成后台自动执行的模式。再等等哈，感觉再过一周题目应该能差不多能收集齐。

能集齐问题最好了

**Comment by harryhare** [comment]
对了，如果有没有收录的问题，希望能继续贴在这里

**Comment by nerddan** [comment]
我会的

**Comment by nerddan** [comment]
question: 新人积分不够。下面哪些做法正确？
answers: {'1': '分享干货、签到答题、参加活动等，争取早日攒够积分。', '3': '想各种办法绕开积分限制，比如要求楼主私下把信息发给我', '4': '注册个小号，相互加分（嘿嘿，地里有后台系统检测哦）', '2': '到处发帖抱怨积分不够、看不到，没准会有帮助呢。'}

**Comment by Sduby22** [comment]
question: 遇到不文明言论，如何合理应对？
answers: {'4': '点楼层内的“反对"', '1': '这些都是', '3': '严于律己，不因为别人言行不文
明而以同样方式还以颜色。', '2': '点楼层内”举报": 举报不文明内容'}
answer not found: 这些违反论坛规则，被封号了怎么办？都是

**Comment by harryhare** [comment]
> question: 遇到不文明言论，如何合理应对？
> answers: {'4': '点楼层内的“反对"', '1': '这些都是', '3': '严于律己，不因为别人言行不文
> 明而以同样方式还以颜色。', '2': '点楼层内”举报": 举报不文明内容'}
> answer not found: 这些违反论坛规则，被封号了怎么办？都是

已修复
